# Generated by Django 6.0.7 on 2026-08-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprint3d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Ej: 10x10x15 cm', max_length=100, null=True),
        ),
    ]
