# Generated by Django 6.0.7 on 2026-08-01 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprint3d', '0002_product_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='¿Está de oferta?'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio rebajado', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='print_time_hours',
            field=models.FloatField(blank=True, help_text='Tiempo de impresión en horas decimales (ej. 2.5 = 2h 30m)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_grams',
            field=models.FloatField(blank=True, help_text='Peso estimado en gramos (incluyendo soportes)', null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('is_cover', models.BooleanField(default=False, help_text='¿Es la imagen principal?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='proprint3d.product')),
            ],
        ),
    ]
