# Generated by Django 6.0.7 on 2026-08-01 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprint3d', '0003_product_is_on_sale_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_costs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Otros costes (Pintura, cajas, etc. en €)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='print_time_minutes',
            field=models.IntegerField(blank=True, help_text='Tiempo de impresión extra en minutos (ej. 30)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='print_time_hours',
            field=models.FloatField(blank=True, help_text='Tiempo de impresión en horas (ej. 2)', null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(help_text='Fecha de Pedido')),
                ('quantity', models.IntegerField(default=1, help_text='Cantidad')),
                ('description', models.CharField(help_text='Descripción del Pedido (Ej. Fiat Panda Rally)', max_length=250)),
                ('client_name', models.CharField(help_text='Nombre de la Persona', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio Final Cobrado (€)', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Coste Total Producción (€)', max_digits=10)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Impreso', 'Impreso'), ('Enviado', 'Enviado'), ('Cobrado', 'Cobrado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('deadline', models.DateField(blank=True, help_text='Fecha límite', null=True)),
                ('platform', models.CharField(choices=[('Wallapop Elyest', 'Wallapop Elyest'), ('Vinted', 'Vinted'), ('Web', 'Web'), ('Directo', 'Directo'), ('Otro', 'Otro')], default='Wallapop Elyest', max_length=50)),
                ('shipping', models.CharField(choices=[('Inpost', 'Inpost'), ('Correos', 'Correos'), ('GLS', 'GLS'), ('En mano', 'En mano'), ('Otro', 'Otro')], default='Inpost', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proprint3d.product')),
            ],
        ),
    ]
