# Generated by Django 6.0.7 on 2026-08-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprint3d', '0004_product_extra_costs_product_print_time_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, help_text='Descripción del Pedido (Ej. Fiat Panda Rally)', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio Final Cobrado (€)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizado', 'Realizado'), ('Pdt de envío', 'Pdt de envío'), ('Pdt. entrega', 'Pdt. entrega'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cobrado', 'Cobrado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
    ]
