# Generated by Django 6.0.7 on 2026-08-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprint3d', '0005_alter_order_description_alter_order_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Nombre del cliente', max_length=150)),
                ('text', models.TextField(help_text='Texto de la valoración')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Puntuación (1-5 estrellas)')),
                ('is_active', models.BooleanField(default=True, help_text='¿Mostrar en la web pública?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
