# Generated by Django 6.0.7 on 2026-08-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprint3d', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='include_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax_name',
            field=models.CharField(default='IVA incl.', max_length=50),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
    ]
