# Generated by Django 6.0.7 on 2026-10-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprint3d', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_costs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Otros costes por unidad (€)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='print_time_hours',
            field=models.FloatField(blank=True, help_text='Horas de impresión por unidad', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='print_time_minutes',
            field=models.IntegerField(blank=True, help_text='Minutos extra de impresión por unidad', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Coste Unitario Producción (€)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio Unitario Cobrado (€)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='weight_grams',
            field=models.FloatField(blank=True, help_text='Peso estimado en gramos por unidad', null=True),
        ),
    ]
