# Generated by Django 6.0.7 on 2026-10-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprint3d', '0009_order_extra_costs_order_print_time_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Presupuestado', 'Presupuestado'), ('Realizado', 'Realizado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cobrado', 'Cobrado'), ('Cancelado', 'Cancelado')], default='Presupuestado', max_length=20),
        ),
    ]
