# Generated by Django 6.0.7 on 2026-10-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprint3d', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(blank=True, help_text='Fecha de Entrega', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_date',
            field=models.DateField(blank=True, help_text='Fecha de Cobro', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(blank=True, help_text='Fecha de Envío', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform',
            field=models.CharField(blank=True, choices=[('Wallapop', 'Wallapop'), ('Wallapop Elyest', 'Wallapop Elyest'), ('Vinted', 'Vinted'), ('Web', 'Web'), ('Directo', 'Directo'), ('Otro', 'Otro')], default='', help_text='Plataforma de venta', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(blank=True, choices=[('Inpost', 'Inpost'), ('Correos', 'Correos'), ('GLS', 'GLS'), ('En mano', 'En mano'), ('Otro', 'Otro')], default='', help_text='Método de envío', max_length=50, null=True),
        ),
    ]
