# Generated by Django 6.0.7 on 2026-10-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprint3d', '0011_order_delivered_date_order_paid_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_file',
            field=models.FileField(blank=True, help_text='Archivo 3D (.stl, .3mf, .step, .zip) accesible solo por administradores', null=True, upload_to='models_3d/'),
        ),
    ]
